const state={plugins:[],config:null,scanId:null,poll:null,ruleId:null,selectionProgrammatic:false,scanMode:'normal',parameterCandidates:[],clientTLSFile:'',clientTLSFormat:'',clientTLSName:'',signatureMode:'',signatureScript:'',signatureName:'',replayMode:'single',replayId:null,replayPoll:null,replayPage:1,replayPageSize:50,replayDictionary:[],httpHistory:[],httpHistoryIndex:-1};
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
const lines=value=>String(value||'').split(/\r?\n|,/).map(v=>v.trim()).filter(Boolean);
const regexLines=value=>String(value||'').split(/\r?\n/).map(v=>v.trim()).filter(Boolean);
const setLines=(id,values)=>$(id).value=(values||[]).join('\n');

async function api(path,options={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});let data={};try{data=await response.json()}catch{}if(!response.ok)throw new Error(data.error||`请求失败 (${response.status})`);return data}
function toast(message,error=false){const node=$('toast');node.textContent=message;node.className=`toast show${error?' error':''}`;clearTimeout(node.timer);node.timer=setTimeout(()=>node.className='toast',2600)}
function formatTime(ms){const seconds=Math.floor((ms||0)/1000);return seconds<60?`${seconds}s`:`${Math.floor(seconds/60)}m ${seconds%60}s`}

$('client-tls-upload').addEventListener('click',()=>$('client-tls-file-input').click());
$('client-tls-file-input').addEventListener('change',async event=>{
  const file=event.target.files?.[0];if(!file)return;
  if(file.size<1||file.size>2000000){event.target.value='';return toast('客户端 TLS 证书必须小于 2 MiB',true)}
  const extension=(file.name.split('.').pop()||'').toLowerCase();
  if(!['pem','pfx','p12'].includes(extension)){event.target.value='';return toast('仅支持 PEM、PFX 或 P12 文件',true)}
  const button=$('client-tls-upload');button.disabled=true;button.textContent='正在上传…';
  try{
    const form=new FormData();form.append('file',file);
    const response=await fetch('/api/v1/client-tls-files',{method:'POST',body:form});
    let data={};try{data=await response.json()}catch{}
    if(!response.ok)throw new Error(data.error||`证书上传失败 (${response.status})`);
    state.clientTLSFile=data.client_tls_file;state.clientTLSFormat=data.format;state.clientTLSName=file.name;
    $('client-tls-name').textContent=file.name;$('client-tls-clear').classList.remove('hidden');
    $('client-tls-password').classList.toggle('hidden',extension==='pem');
    toast('客户端 TLS 证书已上传，本次测试和扫描将带证发送');
  }catch(error){event.target.value='';toast(error.message,true)}
  finally{button.disabled=false;button.textContent='上传证书'}
});
$('client-tls-clear').addEventListener('click',()=>{
  state.clientTLSFile='';state.clientTLSFormat='';state.clientTLSName='';
  $('client-tls-file-input').value='';$('client-tls-password').value='';
  $('client-tls-password').classList.add('hidden');$('client-tls-clear').classList.add('hidden');$('client-tls-name').textContent='未选择';
});
function withClientTLS(payload){const result=state.clientTLSFile?{...payload,client_tls_file:state.clientTLSFile,client_tls_password:$('client-tls-password').value}:payload;return withSignature(result)}
function withSignature(payload){const mode=$('signature-mode')?.value||'';if(!mode)return payload;const signature={mode};if(mode==='http'){signature.endpoint=$('signature-endpoint').value.trim();}else{signature.script=state.signatureScript;}return{...payload,signature}}
function withScanOptions(payload){return withSignature(withClientTLS(payload))}
$('signature-mode').addEventListener('change',event=>{const mode=event.target.value;$('signature-endpoint').classList.toggle('hidden',mode!=='http');$('signature-upload').classList.toggle('hidden',mode!=='local_js');$('signature-name').classList.toggle('hidden',mode!=='local_js');$('signature-clear').classList.toggle('hidden',mode!=='local_js'||!state.signatureScript);if(mode==='http')$('signature-endpoint').focus()});
$('signature-upload').addEventListener('click',()=>$('signature-file-input').click());
$('signature-file-input').addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file)return;if(file.size<1||file.size>2000000){event.target.value='';return toast('签名脚本必须小于 2 MiB',true)}if(!file.name.toLowerCase().endsWith('.js')){event.target.value='';return toast('仅支持 .js 签名脚本',true)}const button=$('signature-upload');button.disabled=true;button.textContent='正在上传…';try{const form=new FormData();form.append('file',file);const response=await fetch('/api/v1/signature-files',{method:'POST',body:form});let data={};try{data=await response.json()}catch{}if(!response.ok)throw new Error(data.error||`签名脚本上传失败 (${response.status})`);state.signatureScript=data.signature_script;state.signatureName=file.name;$('signature-name').textContent=file.name;$('signature-clear').classList.remove('hidden');toast('签名脚本已上传')}catch(error){event.target.value='';toast(error.message,true)}finally{button.disabled=false;button.textContent='上传 JS'}});
$('signature-clear').addEventListener('click',()=>{state.signatureScript='';state.signatureName='';$('signature-file-input').value='';$('signature-clear').classList.add('hidden');$('signature-name').textContent='未选择'});
function setReplayMode(mode){state.replayMode=mode==='brute'?'brute':'single';$('connectivity-button').textContent=state.replayMode==='brute'?'爆破':'发送';$('brute-options').classList.toggle('hidden',state.replayMode!=='brute');$('replay-menu').classList.add('hidden');$('replay-status').textContent=state.replayMode==='brute'?'爆破模式':'等待发送'}
$('replay-menu-button').addEventListener('click',event=>{event.stopPropagation();$('replay-menu').classList.toggle('hidden')});
document.addEventListener('click',event=>{if(!$('replay-menu')?.contains(event.target)&&event.target!==$('replay-menu-button'))$('replay-menu')?.classList.add('hidden')});
document.querySelectorAll('#replay-menu button').forEach(button=>button.addEventListener('click',()=>setReplayMode(button.dataset.replayMode)));
$('brute-dictionary-file').addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file){state.replayDictionary=[];$('brute-dictionary-meta').textContent='未选择字典';return}if(file.size>2_000_000){event.target.value='';state.replayDictionary=[];return toast('字典文件不能超过 2 MiB',true)}const text=await file.text();state.replayDictionary=text.split(/\r?\n/).map(v=>v.replace(/\r/g,'')).filter(v=>v.length>0).slice(0,20000);$('brute-dictionary-meta').textContent=`${file.name} · ${state.replayDictionary.length} 条`;toast('字典已载入')});

function viewFromURL(){const params=new URLSearchParams(location.search);if(params.get('assets')==='true')return'assets';if(params.get('single')==='true')return'scan';if(params.get('config')==='true')return'settings';if(params.get('version')==='true')return'version';if(params.get('guide')==='true')return'guide';return'proxy'}
function showView(view,updateURL=false){const allowed=['proxy','assets','scan','settings','version','guide'];const selected=allowed.includes(view)?view:'proxy';if(updateURL){const url=new URL(location.href);url.searchParams.delete('assets');url.searchParams.delete('single');url.searchParams.delete('config');url.searchParams.delete('version');url.searchParams.delete('guide');if(selected==='assets')url.searchParams.set('assets','true');if(selected==='scan')url.searchParams.set('single','true');if(selected==='settings')url.searchParams.set('config','true');if(selected==='version')url.searchParams.set('version','true');if(selected==='guide')url.searchParams.set('guide','true');history.pushState(null,'',`${url.pathname}${url.search}${url.hash}`)}document.querySelectorAll('.nav-button').forEach(v=>v.classList.toggle('active',v.dataset.view===selected));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`${selected}-view`));window.dispatchEvent(new CustomEvent('happy:viewchange',{detail:{view:selected}}));void ensureViewData(selected)}
document.querySelectorAll('.nav-button').forEach(button=>button.addEventListener('click',()=>showView(button.dataset.view,true)));
window.addEventListener('popstate',()=>showView(viewFromURL()));

let pluginLoad=null,configLoad=null,guideLoad=null,ruleEditorReady=false;
async function ensurePlugins(){if(!pluginLoad)pluginLoad=loadPlugins();return pluginLoad}
async function ensureConfig(){if(!configLoad)configLoad=loadConfig();return configLoad}
async function ensureGuide(){if(!guideLoad)guideLoad=loadGuide();return guideLoad}
async function ensureViewData(view){
  if(view==='scan'){await Promise.all([ensurePlugins(),ensureConfig()]);return}
  if(view==='settings'){await Promise.all([ensurePlugins(),ensureConfig()]);if(!ruleEditorReady){initRuleEditor();ruleEditorReady=true}return}
  if(view==='guide')await ensureGuide();
}
async function init(){const view=viewFromURL();showView(view);try{const health=await api('/api/health');$('health').classList.add('ok');$('health').lastChild.textContent='服务正常'}catch{$('health').lastChild.textContent='服务异常'}await ensureViewData(view)}

async function loadPlugins(){try{const data=await api('/api/v1/plugins');state.plugins=data.plugins;renderPlugins()}catch(error){$('plugin-list').innerHTML=`<div class="skeleton">${esc(error.message)}</div>`}}
const pluginGroups=[
  {name:'SQL 与查询注入',ids:['sqli','sqli_deep','nosql_injection','ldap_injection','xpath_injection']},
  {name:'文件与 XML',ids:['file_read','file_upload','file_upload_execution','xxe','xxe_extended']},
  {name:'身份、权限与会话',ids:['unauthorized','idor','csrf','method_override','mass_assignment','mass_assignment_extended','path_normalization','parameter_confusion','proxy_trust_bypass','jwt_weak','jwt_active','shiro']},
  {name:'代码与表达式执行',ids:['reflected_xss','reflected_xss_deep','ssti','java_expression','java_expression_extended','command_injection','command_injection_oast','command_injection_timing','jndi_injection','java_deserialization','json_polymorphic']},
  {name:'服务端请求与跳转',ids:['ssrf','open_redirect','crlf_injection','host_header_injection']},
  {name:'API、框架与协议配置',ids:['api_exposure','spring_actuator','graphql_security','graphql_alias_abuse','cors','security_headers','http_trace']},
  {name:'响应与业务风险',ids:['sensitive_data','error_disclosure','error_disclosure_extended','sms_abuse']}
];
function pluginCard(item){return `<label class="plugin-item plugin-compact"><input type="checkbox" value="${esc(item.id)}"><span><strong>${esc(item.name)}</strong><small>${esc(item.description)}</small><small class="risk">${esc(riskLabel(item.risk))}</small></span></label>`}
function resetParameterScope(message='插件或报文已改变，请重新点击“参数解析”；留空表示扫描全部可用参数。'){if(!$('scan-parameters'))return;$('scan-parameters').value='';state.parameterCandidates=[];$('parameter-parse-help').textContent=message}
function renderPlugins(){const byId=new Map(state.plugins.map(item=>[item.id,item])),used=new Set(),sections=[];for(const group of pluginGroups){const items=group.ids.map(id=>byId.get(id)).filter(Boolean);items.forEach(item=>used.add(item.id));if(items.length)sections.push(`<section class="plugin-group"><h3>${esc(group.name)}<span>${items.length}</span></h3><div class="plugin-group-grid">${items.map(pluginCard).join('')}</div></section>`)}const others=state.plugins.filter(item=>!used.has(item.id)).sort((a,b)=>a.name.localeCompare(b.name,'zh-CN'));if(others.length)sections.push(`<section class="plugin-group"><h3>其他检测<span>${others.length}</span></h3><div class="plugin-group-grid">${others.map(pluginCard).join('')}</div></section>`);$('plugin-list').innerHTML=sections.join('');document.querySelectorAll('#plugin-list input').forEach(input=>input.addEventListener('change',()=>{resetParameterScope();if(!state.selectionProgrammatic)applyScanMode('custom');else updateSelection()}));applyScanMode(state.scanMode)}
function updateSelection(){const inputs=[...document.querySelectorAll('#plugin-list input')];const count=inputs.filter(v=>v.checked).length;$('selected-count').textContent=`${count} 项已选择`}
document.querySelectorAll('.mode-option').forEach(button=>button.addEventListener('click',()=>applyScanMode(button.dataset.mode)));
function updateModeUI(mode){const labels={passive:'<strong>Passive</strong>：只勾选被动响应分析插件，不发送漏洞 Payload。',normal:'<strong>Normal</strong>：勾选常见高价值插件；每个插件的能力固定，可继续手动增减。',deep:'<strong>Deep</strong>：勾选全部插件，包括时间差分、回连和扩展能力插件。',custom:'<strong>Custom</strong>：完全使用当前手工勾选的插件组合。'};document.querySelectorAll('.mode-option').forEach(button=>{const selected=button.dataset.mode===mode;button.classList.toggle('active',selected);button.setAttribute('aria-checked',String(selected))});$('scan-mode-help').innerHTML=labels[mode]||labels.custom}
function applyScanMode(mode){const allowed=['passive','normal','deep','custom'];mode=allowed.includes(mode)?mode:'custom';if(state.scanMode!==mode&&$('scan-parameters'))resetParameterScope();state.scanMode=mode;updateModeUI(mode);const normalActive=new Set((state.config?.normal_plugins||[]).map(String));if(mode==='custom'){updateSelection();return}state.selectionProgrammatic=true;document.querySelectorAll('#plugin-list input').forEach(input=>{const plugin=state.plugins.find(item=>item.id===input.value);const passive=plugin?.risk==='passive';input.checked=(mode==='deep'&&input.value!=='sqli')||(mode==='passive'&&passive)||(mode==='normal'&&normalActive.has(input.value))});state.selectionProgrammatic=false;updateSelection()}
const httpRequestEditor=window.HappyScanEditor.create($('http-request'),{
  placeholder:'POST /api/user/query HTTP/1.1\nHost: test.example.local\nContent-Type: application/json\nCookie: JSESSIONID=...\n\n{"id":"1"}',
  onChange:value=>{$('request-size').textContent=`${value.length.toLocaleString()} 字符`;if(state.parameterCandidates.length)resetParameterScope();updateHTTPHistoryButtons()}
});
const httpViewers=new Map();
function httpRequestValue(){return httpRequestEditor.getValue()}
function setHTTPRequest(value){httpRequestEditor.setValue(value)}
function setHTTPViewer(id,value){let editor=httpViewers.get(id);if(!editor){editor=window.HappyScanEditor.create($(id),{readOnly:true});httpViewers.set(id,editor)}editor.setValue(value||'')}
function updateHTTPHistoryButtons(){const back=$('http-history-back'),forward=$('http-history-forward');if(!back||!forward)return;back.disabled=state.httpHistoryIndex<=0;forward.disabled=state.httpHistoryIndex<0||state.httpHistoryIndex>=state.httpHistory.length-1;const label=state.httpHistory.length?`历史 ${state.httpHistoryIndex+1}/${state.httpHistory.length}`:'暂无历史';back.title=`上一份报文（${label}）`;forward.title=`下一份报文（${label}）`}
function parseParameterScopeText(value){const seen=new Set(),result=[];for(const raw of String(value||'').split(/[\r\n,]+/)){let selector=raw.trim();if(selector.startsWith('[')&&selector.endsWith(']'))selector=selector.slice(1,-1).trim();if(!selector)continue;const key=selector.toLowerCase();if(!seen.has(key)){seen.add(key);result.push(selector)}}return result}
function selectedScanPluginIDs(){return[...document.querySelectorAll('#plugin-list input:checked')].map(input=>input.value)}
function scanModeValue(){return state.scanMode==='deep'?'deep':state.scanMode==='passive'?'passive':'standard'}
function renderParameterCandidates(data,selectedIDs){const groups=data?.plugin_parameters||{},ids=selectedIDs.length?selectedIDs:Object.keys(groups);const seen=new Set(),selectors=[];for(const id of ids){for(const item of groups[id]||[]){const selector=String(item.selector||item.name||item.path||'').trim();if(!selector||seen.has(selector.toLowerCase()))continue;seen.add(selector.toLowerCase());selectors.push(selector)}}$('scan-parameters').value=selectors.join('\n');state.parameterCandidates=selectors;if(selectors.length){$('parameter-parse-help').textContent=`已解析 ${selectors.length} 个可扫描参数；持久配置排除项不会显示，编辑后仅扫描保留项。位置限定参数直接显示为 query:name、json:path。`}else{$('parameter-parse-help').textContent='当前插件没有可变异参数，或参数已被持久配置排除；留空表示扫描全部可用参数。'}}
async function parseScanParameters(){const http=httpRequestValue().trim(),scheme=$('request-scheme').value,scan_type=selectedScanPluginIDs();if(!http)return toast('请先粘贴 HTTP 报文',true);if(!scan_type.length)return toast('请至少选择一种漏洞类型',true);const button=$('parse-parameters');button.disabled=true;button.textContent='解析中…';try{const data=await api('/api/v1/parse',{method:'POST',body:JSON.stringify(withClientTLS({http,scheme,scan_type,mode:scanModeValue()}))});renderParameterCandidates(data,scan_type);$('parse-result').textContent=`已解析 ${state.parameterCandidates.length} 个参数（未扫描）`;toast('参数解析完成，未发送漏洞请求')}catch(error){toast(error.message,true)}finally{button.disabled=false;button.textContent='参数解析'}}
function decodeFormComponent(value){try{return decodeURIComponent(String(value).replace(/\+/g,' '))}catch{return value}}
function decodeTargetPreview(target){const hashIndex=target.indexOf('#'),hash=hashIndex>=0?target.slice(hashIndex):'',withoutHash=hashIndex>=0?target.slice(0,hashIndex):target;const queryIndex=withoutHash.indexOf('?');if(queryIndex<0)return withoutHash.split('/').map(decodeFormComponent).join('/')+hash;const path=withoutHash.slice(0,queryIndex).split('/').map(decodeFormComponent).join('/'),query=withoutHash.slice(queryIndex+1).split('&').map(pair=>{const index=pair.indexOf('=');return index<0?decodeFormComponent(pair):`${decodeFormComponent(pair.slice(0,index))}=${decodeFormComponent(pair.slice(index+1))}`}).join('&');return `${path}?${query}${hash}`}
function decodeFormBodyPreview(body){return body.split('&').map(pair=>{const index=pair.indexOf('=');return index<0?decodeFormComponent(pair):`${decodeFormComponent(pair.slice(0,index))}=${decodeFormComponent(pair.slice(index+1))}`}).join('&')}
function decodeHTTPRequestPreview(raw){const text=String(raw||'');if(!text)return{text:'',changed:false};const separator=text.indexOf('\r\n\r\n'),lineSeparator=separator>=0?'\r\n':'\n',splitAt=separator>=0?separator:text.indexOf('\n\n'),head=splitAt>=0?text.slice(0,splitAt):text,body=splitAt>=0?text.slice(splitAt+(separator>=0?4:2)):'';const lines=head.split(/\r?\n/),requestLine=lines[0]||'',parts=requestLine.split(' ');if(parts.length>=2)parts[1]=decodeTargetPreview(parts[1]);lines[0]=parts.join(' ');const contentType=lines.find(line=>/^content-type\s*:/i.test(line))||'';let decodedBody=body;if(/application\/x-www-form-urlencoded/i.test(contentType))decodedBody=decodeFormBodyPreview(body);const result=splitAt>=0?lines.join(lineSeparator)+lineSeparator+lineSeparator+decodedBody:lines.join(lineSeparator);return{text:result,changed:result!==text}}
function recordHTTPHistory(request,response,title,meta,error=false){const entry={request:String(request||''),response:String(response||''),title:String(title||'返回报文'),meta:String(meta||''),error};const current=state.httpHistory[state.httpHistoryIndex];if(current&&current.request===entry.request&&current.response===entry.response&&current.title===entry.title&&current.meta===entry.meta&&current.error===entry.error){updateHTTPHistoryButtons();return}if(state.httpHistoryIndex<state.httpHistory.length-1)state.httpHistory=state.httpHistory.slice(0,state.httpHistoryIndex+1);state.httpHistory.push(entry);if(state.httpHistory.length>100)state.httpHistory.shift();state.httpHistoryIndex=state.httpHistory.length-1;updateHTTPHistoryButtons()}
function showHTTPHistory(index){if(index<0||index>=state.httpHistory.length)return;const entry=state.httpHistory[index];state.httpHistoryIndex=index;setHTTPRequest(entry.request);$('request-size').textContent=`${entry.request.length.toLocaleString()} 字符`;$('response-placeholder').classList.add('hidden');$('brute-result').classList.add('hidden');const panel=$('connectivity-result');panel.classList.remove('hidden');panel.classList.toggle('error',entry.error);$('connectivity-title').textContent=entry.title;$('connectivity-meta').textContent=entry.meta;setHTTPViewer('connectivity-response',entry.response||(entry.error?'返回失败':'返回为空'));$('replay-status').textContent=`历史 ${index+1}/${state.httpHistory.length}`;updateHTTPHistoryButtons()}
function stepHTTPHistory(delta){showHTTPHistory(state.httpHistoryIndex+delta)}
$('http-history-back').addEventListener('click',()=>stepHTTPHistory(-1));
$('http-history-forward').addEventListener('click',()=>stepHTTPHistory(1));
updateHTTPHistoryButtons();

$('connectivity-button').addEventListener('click',()=>state.replayMode==='brute'?startBruteReplay():testConnectivity());
async function testConnectivity(){const http=httpRequestValue().trim();const scheme=$('request-scheme').value;if(!http)return toast('请先粘贴 HTTP 报文',true);clearReplayPoll();const button=$('connectivity-button');const panel=$('connectivity-result');$('response-placeholder').classList.add('hidden');$('brute-result').classList.add('hidden');button.disabled=true;button.textContent='正在发送…';panel.classList.remove('hidden','error');$('connectivity-title').textContent='正在发送报文';$('connectivity-meta').textContent='等待目标响应';setHTTPViewer('connectivity-response','');$('replay-status').textContent='发送中';try{const data=await api('/api/v1/connectivity',{method:'POST',body:JSON.stringify(withClientTLS({http,scheme}))});if(data.ok){const title=`HTTP ${data.status_code} · 原始报文可达`,meta=`${String(data.scheme).toUpperCase()} · ${data.elapsed_ms}ms${data.auto_fallback?' · 自动协议已切换':''}${state.clientTLSFile?' · mTLS 证书已启用':''}`,raw=data.raw_response||data.body||'';$('connectivity-title').textContent=title;$('connectivity-meta').textContent=meta;setHTTPViewer('connectivity-response',raw);$('replay-status').textContent=`HTTP ${data.status_code} · ${data.elapsed_ms}ms`;recordHTTPHistory(http,raw,title,meta);toast('原始报文发送成功')}else{const title='原始报文发送失败',meta=`${String(data.scheme||scheme).toUpperCase()} · ${data.elapsed_ms||0}ms`,error=data.error||'未知网络错误';panel.classList.add('error');$('connectivity-title').textContent=title;$('connectivity-meta').textContent=meta;setHTTPViewer('connectivity-response',error);$('replay-status').textContent='发送失败';recordHTTPHistory(http,'',title,meta,error);toast(error,true)}}catch(error){const title='原始报文发送失败',meta='请求未完成';panel.classList.add('error');$('connectivity-title').textContent=title;$('connectivity-meta').textContent=meta;setHTTPViewer('connectivity-response',error.message);$('replay-status').textContent='发送失败';recordHTTPHistory(http,'',title,meta,error.message);toast(error.message,true)}finally{button.disabled=false;button.textContent=state.replayMode==='brute'?'爆破':'发送'}}
function clearReplayPoll(){if(state.replayPoll){clearInterval(state.replayPoll);state.replayPoll=null}}
function replayPayload(){return withClientTLS({http:httpRequestValue().trim(),scheme:$('request-scheme').value,concurrency:Number($('brute-concurrency').value||10),repeat:Number($('brute-repeat').value||10),max_requests:Number($('brute-max-requests').value||10000),dictionary:state.replayDictionary})}
async function startBruteReplay(){const http=httpRequestValue().trim();if(!http)return toast('请先粘贴 HTTP 报文',true);const button=$('connectivity-button');clearReplayPoll();button.disabled=true;button.textContent='正在创建…';$('response-placeholder').classList.add('hidden');$('connectivity-result').classList.add('hidden');$('brute-result').classList.remove('hidden');setHTTPViewer('brute-response-detail','');$('brute-result-rows').innerHTML='';$('brute-summary').textContent='正在展开模板并创建并发任务';try{const created=await api('/api/v1/replays',{method:'POST',body:JSON.stringify(replayPayload())});state.replayId=created.replay_id;state.replayPage=1;$('replay-status').textContent=`爆破中 · ${created.total} 个请求`;toast(`爆破任务已创建：${created.total} 个请求，并发 ${created.concurrency}`);await pollReplay();state.replayPoll=setInterval(pollReplay,900)}catch(error){$('brute-summary').textContent=error.message;$('replay-status').textContent='爆破失败';toast(error.message,true);button.disabled=false;button.textContent='爆破'}}
async function pollReplay(){if(!state.replayId)return;try{const data=await api(`/api/v1/replays/${state.replayId}?page=${state.replayPage}&page_size=${state.replayPageSize}`);renderReplay(data);if(['completed','failed','cancelled'].includes(data.status)){clearReplayPoll();$('connectivity-button').disabled=false;$('connectivity-button').textContent='爆破';if(data.status==='completed')toast('爆破任务完成');if(data.error)toast(data.error,true)}}catch(error){clearReplayPoll();$('connectivity-button').disabled=false;$('connectivity-button').textContent='爆破';toast(error.message,true)}}
function renderReplay(data){const pages=Math.max(1,Math.ceil((data.result_count||0)/state.replayPageSize));$('replay-status').textContent=`${replayStatusLabel(data.status)} · ${data.completed}/${data.total}`;$('brute-summary').textContent=`${replayStatusLabel(data.status)} · 已完成 ${data.completed}/${data.total} · 失败 ${data.failed||0} · 并发 ${data.concurrency} · ${formatTime(data.elapsed_ms)}${data.truncated?' · 已按最多请求数截断':''}`;$('brute-page').textContent=`${state.replayPage} / ${pages}`;$('brute-prev').disabled=state.replayPage<=1;$('brute-next').disabled=state.replayPage>=pages;const rows=(data.results||[]).map(item=>`<tr data-result-id="${esc(item.id)}"><td>${item.index}</td><td title="${esc(item.payload)}">${esc(item.payload)}</td><td class="${item.error?'brute-error':''}">${item.error?'ERR':item.status_code}</td><td>${Number(item.response_bytes||0).toLocaleString()}</td><td>${item.elapsed_ms}ms</td></tr>`).join('');$('brute-result-rows').innerHTML=rows||'<tr><td colspan="5">等待响应返回…</td></tr>';document.querySelectorAll('#brute-result-rows tr[data-result-id]').forEach(row=>row.addEventListener('click',()=>loadReplayDetail(row.dataset.resultId)))}
function replayStatusLabel(value){return({queued:'排队中',running:'爆破中',completed:'已完成',failed:'失败',cancelled:'已取消',cancelling:'取消中'})[value]||value}
$('brute-prev').addEventListener('click',()=>{if(state.replayPage>1){state.replayPage--;pollReplay()}});
$('brute-next').addEventListener('click',()=>{state.replayPage++;pollReplay()});
async function loadReplayDetail(id){if(!state.replayId||!id)return;document.querySelectorAll('#brute-result-rows tr').forEach(row=>row.classList.toggle('selected',row.dataset.resultId===id));setHTTPViewer('brute-response-detail','正在加载返回报文…');try{const data=await api(`/api/v1/replays/${state.replayId}/results/${id}`);const result=data.result||{};setHTTPViewer('brute-response-detail',result.raw_response||result.error||'')}catch(error){setHTTPViewer('brute-response-detail',error.message);toast(error.message,true)}}

$('scan-button').addEventListener('click',startScan);
$('parse-parameters').addEventListener('click',parseScanParameters);
async function startScan(){const http=httpRequestValue().trim();const scheme=$('request-scheme').value;const scan_type=selectedScanPluginIDs();if(!http)return toast('请先粘贴 HTTP 报文',true);if(!scan_type.length)return toast('请至少选择一种漏洞类型',true);$('scan-button').disabled=true;$('results-section').classList.add('hidden');$('progress-panel').classList.remove('hidden');$('progress-title').textContent='正在生成扫描计划';const mode=scanModeValue();const scope=parseParameterScopeText($('scan-parameters').value);const payload=withClientTLS({http,scheme,scan_type,mode});if(scope.length)payload.parameter_scope=scope;try{const plan=await api('/api/v1/plan',{method:'POST',body:JSON.stringify(payload)});renderPlan(plan);const data=await api('/api/v1/scan',{method:'POST',body:JSON.stringify(payload)});state.scanId=data.scan_id;toast(`扫描任务已创建，计划约 ${plan.estimated_requests} 个请求${scope.length?`，已限制 ${scope.length} 个参数`:''}`);clearInterval(state.poll);await pollScan();state.poll=setInterval(pollScan,900)}catch(error){toast(error.message,true);$('progress-panel').classList.add('hidden');$('scan-button').disabled=false}}

function renderPlan(plan){const partial=Object.values(plan.plugins||{}).filter(v=>v.status==='partial').length;const skipped=Object.values(plan.plugins||{}).filter(v=>v.status==='skipped').length;const node=$('plan-summary');node.classList.remove('hidden');node.innerHTML=`<strong>扫描前计划</strong><span>${plan.discovered_points} 个插入点 · 最多 ${plan.estimated_requests} 个计划请求 · 预算 ${plan.request_budget}</span><span class="${plan.complete_within_budget?'plan-ok':'plan-warn'}">${plan.complete_within_budget?'预算足够完整执行':`${partial} 个插件可能部分执行`}${skipped?` · ${skipped} 个不适用插件自动跳过`:''}</span>`}

async function pollScan(){if(!state.scanId)return;try{const scan=await api(`/api/v1/scans/${state.scanId}`);renderProgress(scan);if(['completed','failed','cancelled'].includes(scan.status)){if(!scan.callback_pending){clearInterval(state.poll);state.poll=null;}$('scan-button').disabled=false;await loadResults();}}catch(error){clearInterval(state.poll);state.poll=null;$('scan-button').disabled=false;toast(error.message,true)}}
function renderProgress(scan){const labels={queued:'排队中',running:'扫描中',completed:'已完成',failed:'失败',cancelled:'已取消'};const phases={queued:'等待调度',baseline:'基线校准',scanning:'漏洞插件检测',passive_analysis:'被动响应分析',safe_active:'安全主动探测',oast_confirmation:'离线回连确认',state_changing:'状态变更独占检测',completed:'结果与覆盖分析',failed:'任务失败',cancelled:'任务已取消'};const progress=scan.progress||{};const requestProgress=progress.planned_requests?` · 请求进度 ${progress.resolved_requests||0}/${progress.planned_requests}${progress.requests_skipped?`（收敛跳过 ${progress.requests_skipped}）`:''}`:'';$('status-pill').textContent=labels[scan.status]||scan.status;$('progress-title').textContent=scan.callback_pending?'等待迟到回连，结果可继续更新':(phases[progress.phase]||progress.phase);$('progress-meta').textContent=`任务 ${scan.scan_id.slice(0,18)}… · 当前 ${progress.plugin||'准备中'}${requestProgress}`;$('progress-bar').style.width=`${progress.percent}%`;$('metric-percent').textContent=`${progress.percent}%`;$('metric-requests').textContent=progress.requests_sent;$('metric-findings').textContent=scan.findings_count;$('metric-time').textContent=formatTime(scan.elapsed_ms);$('cancel-button').classList.toggle('hidden',!['queued','running'].includes(scan.status));renderPluginProgress(progress.plugins||{},scan.coverage||{});if(scan.error)toast(scan.error,true)}
$('cancel-button').addEventListener('click',async()=>{if(!state.scanId)return;try{await api(`/api/v1/scans/${state.scanId}/cancel`,{method:'POST',body:'{}'});toast('正在取消任务')}catch(error){toast(error.message,true)}});

async function loadResults(){if(!state.scanId)return;try{const data=await api(`/api/v1/scans/${state.scanId}/result`);$('results-section').classList.remove('hidden');const findings=data.findings||[];const coverage=data.scan.coverage||{};$('result-summary').textContent=`${findings.length} 个发现 · ${formatTime(data.scan.elapsed_ms)} · ${data.scan.progress.requests_sent} 个请求 · ${coverage.complete?'覆盖完整':'覆盖不完整'}`;renderPluginProgress(data.scan.progress.plugins||{},coverage);renderCorrelations(data.scan.correlations||[]);if(!findings.length){$('findings').innerHTML='<div class="empty-result"><strong>未发现符合当前判定阈值的漏洞</strong><p>请结合上方逐插件请求进度判断结论有效范围；灰色、部分或失败的插件不代表目标安全。</p></div>';return}$('findings').innerHTML=findings.map(renderFinding).join('')}catch(error){toast(error.message,true)}}
function renderPluginProgress(progressPlugins={},coverage={}){const target=$('plugin-progress');if(!target)return;const coveragePlugins=coverage.plugins||{};const ids=[...new Set([...Object.keys(progressPlugins),...Object.keys(coveragePlugins)])];target.innerHTML=ids.map(id=>{const live=progressPlugins[id]||{};const item=coveragePlugins[id]||{};const pluginStatus=live.status||item.status||'queued';const completed=Number(live.completed||0);const total=Number(live.total||0);let detail='';if(pluginStatus==='skipped')detail=item.reason||'当前报文不满足插件执行条件';else if(pluginStatus==='partial'||pluginStatus==='failed')detail=item.reason||'插件未完整执行';else if(pluginStatus==='queued')detail='等待执行';else if(pluginStatus==='running')detail='正在发送检测请求';return `<div class="plugin-chip ${esc(pluginStatus)}"><span><strong>${esc(live.name||item.name||id)}</strong><b>${completed}/${total}</b></span>${detail?`<small>${esc(detail)}</small>`:''}</div>`}).join('')}
function renderCorrelations(items){const node=$('correlations');if(!node)return;node.innerHTML=(items||[]).map(item=>`<div class="correlation-card"><strong>关联风险 · ${esc(item.affected)}</strong><span>${esc(item.summary)} · ${item.finding_ids.length} 个发现</span></div>`).join('')}
function renderFinding(item){const evidence=(item.evidence||[]).map(ev=>{const requestRaw=ev.request||'',requestPreview=decodeHTTPRequestPreview(requestRaw),response=ev.response||`HTTP/1.1 ${ev.response_status||''}\r\n\r\n${ev.response_excerpt||''}`;const requestHTML=`<div class="evidence-block"><span class="evidence-label">请求报文（可读预览）</span><pre class="evidence" data-http-viewer>${esc(requestPreview.text)}</pre>${requestPreview.changed?`<details class="evidence-raw"><summary>查看实际发送的 URL 编码报文</summary><pre class="evidence">${esc(requestRaw)}</pre></details>`:''}</div>`;return `<details><summary>${esc(ev.summary)}</summary><div class="evidence-pair">${requestHTML}<div class="evidence-block"><span class="evidence-label">返回报文（原始）</span><pre class="evidence" data-http-viewer>${esc(response)}</pre></div></div></details>`}).join('');const severity=severityLabel(item.severity),confidence=confidenceLabel(item.confidence),category=categoryLabel(item.category);return `<article class="finding ${esc(severityClass(item.severity))}"><div class="finding-head"><h3>${esc(item.title)}</h3><div class="badges"><span class="badge severity">${esc(severity)}</span><span class="badge">${esc(confidence)}</span><span class="badge category">${esc(category)} · 可信分 ${Number(item.score||0)}</span></div></div><div class="finding-meta">${esc(item.plugin_id)} · ${esc(item.affected)}${item.correlation_id?` · 关联 ${esc(item.correlation_id)}`:''}</div><p>${esc(item.description)}</p><p><strong>修复建议：</strong>${esc(item.remediation)}</p>${evidence}</article>`}
function severityLabel(value){return({info:'提示',low:'低危',medium:'中危',high:'高危',critical:'严重','提示':'提示','低危':'低危','中危':'中危','高危':'高危','严重':'严重'})[value]||value||'提示'}
function confidenceLabel(value){return({tentative:'待确认',firm:'较确定',certain:'已确认','待确认':'待确认','较确定':'较确定','已确认':'已确认'})[value]||value||'待确认'}
function categoryLabel(value){return({confirmed:'确认漏洞',probable:'疑似漏洞',exposure:'配置暴露',informational:'信息提示','确认漏洞':'确认漏洞','疑似漏洞':'疑似漏洞','配置暴露':'配置暴露','信息提示':'信息提示'})[value]||value||'疑似漏洞'}
function severityClass(value){return({严重:'critical',高危:'high',中危:'medium',低危:'low',提示:'info'})[value]||String(value||'info').toLowerCase()}
function riskLabel(value){return({passive:'被动分析',active:'主动探测','state-changing':'状态变更','adjacent-path':'相邻路径'})[value]||value}

async function loadConfig(){try{const data=await api('/api/v1/config');state.config=data.config;$('config-path').textContent=data.config_file;fillConfig(state.config);setLines('cfg-normal-plugins',state.config.normal_plugins||[]);applyScanMode(state.scanMode)}catch(error){toast(error.message,true)}}
function businessLiteral(value){return String(value||'').replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function businessDisplay(value){const text=String(value||'');if(/code/i.test(text)&&/(?:0|200|000000)/.test(text))return 'code';if(/success/i.test(text)&&/true/i.test(text))return 'success';return text.replace(/\\([.*+?^${}()|[\]\\])/g,'$1')}
function businessKeywords(c,outcome){
  const rules=(c.business_rules||[]).filter(rule=>rule.outcome===outcome&&rule.pattern).map(rule=>rule.pattern);
  if(rules.length)return rules;
  return outcome==='success'?(c.success_patterns||[]):(c.business_failure_patterns||[]);
}
// Keep the old response fields as a wire-compatible fallback while presenting
// a simple keyword editor. The backend still receives the existing rule model.
function fillConfig(c){
  const success=businessKeywords(c,'success'),failure=businessKeywords(c,'failure');
  $('cfg-business-success').value=success.map(businessDisplay).join('\n');$('cfg-business-failure').value=failure.map(businessDisplay).join('\n');
  $('cfg-sms-attempts').value=c.sms?.attempts??30;$('cfg-sms-threshold').value=c.sms?.threshold??5;$('cfg-sms-window').value=c.sms?.window_seconds??60;$('cfg-callback-wait').value=c.callback_wait_seconds??8;$('cfg-callback-late').value=c.callback_late_seconds??120;$('cfg-listen').value=c.listen;$('cfg-transport').value=c.transport_mode||'normalized';$('cfg-proxy').value=c.proxy_url||'';setLines('cfg-hosts',c.allowed_hosts);$('cfg-verify-tls').checked=c.verify_tls;$('cfg-redirects').checked=c.follow_redirects;$('cfg-private').checked=c.allow_private_targets;$('cfg-auth-expected').checked=c.authorization_expected;$('cfg-redact').checked=c.redact_evidence;$('cfg-timeout').value=c.timeout_seconds;$('cfg-concurrency').value=c.max_concurrency;$('cfg-active-scans').value=c.max_active_scans;$('cfg-queued-scans').value=c.max_queued_scans||32;$('cfg-rps').value=c.requests_per_second;$('cfg-global-concurrency').value=c.global_max_concurrency||32;$('cfg-host-concurrency').value=c.per_host_concurrency||12;$('cfg-global-rps').value=c.global_requests_per_second||40;$('cfg-max-requests').value=c.max_requests;$('cfg-max-response').value=c.max_response_bytes;$('cfg-baselines').value=c.baseline_samples;$('cfg-ttl').value=c.task_ttl_minutes;$('cfg-scans-minute').value=c.max_scans_per_minute||60;$('cfg-shared-mode').checked=Boolean(c.shared_service_mode);setLines('cfg-session-keys',(c.session_identifiers||[]).map(v=>typeof v==='string'?v:v.name));setLines('cfg-csrf-headers',c.csrf_header_names);setLines('cfg-excluded-params',c.excluded_parameter_names);$('cfg-callback-listen').value=c.callback_listen||'0.0.0.0:61166';$('cfg-callback').value=c.callback_base_url||'';$('cfg-callback-ldap-listen').value=c.callback_ldap_listen||'0.0.0.0:61167';$('cfg-callback-ldap').value=c.callback_ldap_base_url||'';$('cfg-callback-max-connections').value=c.callback_max_connections||128;$('cfg-sqli-errors').value=(c.sqli_error_patterns||[]).join('\n');$('cfg-sqli-error-confidence').value=c.sqli_error_confidence||'firm';
}
$('cfg-sqli-errors').addEventListener('input',()=>{if(state.config)state.config.sqli_error_patterns=regexLines($('cfg-sqli-errors').value)});
$('cfg-normal-plugins').addEventListener('input',()=>{if(state.config)state.config.normal_plugins=lines($('cfg-normal-plugins').value)});

window.__simpleSettingsSubmit=async event=>{
  try{captureRule()}catch(error){toast(error.message,true);return}
  const success=regexLines($('cfg-business-success').value),failure=regexLines($('cfg-business-failure').value);
  const business_rules=[...success.map(value=>({name:'业务成功关键词',pattern:businessLiteral(value),outcome:'success'})),...failure.map(value=>({name:'业务失败关键词',pattern:businessLiteral(value),outcome:'failure'}))];
  const password=$('cfg-password').value;if(!password){toast('请输入配置保存密码',true);$('cfg-password').focus();return}
  const base=state.config||{};const session_identifiers=lines($('cfg-session-keys').value);
  const cfg={...base,business_rules,success_patterns:success.map(businessLiteral),sms:{attempts:Number($('cfg-sms-attempts').value),threshold:Number($('cfg-sms-threshold').value),window_seconds:Number($('cfg-sms-window').value)},callback_wait_seconds:Number($('cfg-callback-wait').value),callback_late_seconds:Number($('cfg-callback-late').value),listen:$('cfg-listen').value.trim(),default_scheme:'https',scan_mode:base.scan_mode||'standard',transport_mode:$('cfg-transport').value,proxy_url:$('cfg-proxy').value.trim(),allowed_hosts:lines($('cfg-hosts').value),verify_tls:$('cfg-verify-tls').checked,follow_redirects:$('cfg-redirects').checked,allow_private_targets:$('cfg-private').checked,authorization_expected:$('cfg-auth-expected').checked,redact_evidence:$('cfg-redact').checked,timeout_seconds:Number($('cfg-timeout').value),max_concurrency:Number($('cfg-concurrency').value),max_active_scans:Number($('cfg-active-scans').value),max_queued_scans:Number($('cfg-queued-scans').value),requests_per_second:Number($('cfg-rps').value),global_max_concurrency:Number($('cfg-global-concurrency').value),per_host_concurrency:Number($('cfg-host-concurrency').value),global_requests_per_second:Number($('cfg-global-rps').value),max_requests:Number($('cfg-max-requests').value),max_response_bytes:Number($('cfg-max-response').value),baseline_samples:Number($('cfg-baselines').value),task_ttl_minutes:Number($('cfg-ttl').value),max_scans_per_minute:Number($('cfg-scans-minute').value),shared_service_mode:$('cfg-shared-mode').checked,session_identifiers,excluded_parameter_names:lines($('cfg-excluded-params').value),csrf_header_names:lines($('cfg-csrf-headers').value),callback_listen:$('cfg-callback-listen').value.trim(),callback_base_url:$('cfg-callback').value.trim(),callback_ldap_listen:$('cfg-callback-ldap-listen').value.trim(),callback_ldap_base_url:$('cfg-callback-ldap').value.trim(),callback_max_connections:Number($('cfg-callback-max-connections').value),sqli_error_patterns:regexLines($('cfg-sqli-errors').value),sqli_error_confidence:$('cfg-sqli-error-confidence').value,dynamic_patterns:base.dynamic_patterns||[],plugin_rules:state.config.plugin_rules};
  try{const data=await api('/api/v1/config',{method:'PUT',headers:{'X-Jungle-Config-Password':password},body:JSON.stringify(cfg)});state.config=data.config;$('cfg-password').value='';toast(data.restart_required?'配置已保存；监听或全局治理参数将在重启后生效':'配置、插件规则与业务关键词已保存，新任务立即生效')}catch(error){toast(error.message,true)}
};
document.addEventListener('submit',event=>{if(event.target?.id==='settings-form'){event.preventDefault();event.stopImmediatePropagation();void window.__simpleSettingsSubmit(event)}},true);

const configPluginEnglish={
  unauthorized:'Unauthorized Access',sqli:'SQL Injection',sqli_deep:'SQL Injection Deep',sqli_extended:'SQL Injection Extended',sqli_timing:'SQL Time Based',sqli_order_by:'SQL ORDER BY',sqli_limit:'SQL LIMIT/OFFSET',
  xxe:'XML External Entity',xxe_extended:'XXE Extended',file_read:'File Read',file_upload:'File Upload',file_upload_execution:'File Upload Execution',
  reflected_xss:'Reflected XSS',reflected_xss_deep:'Reflected XSS Deep',ssrf:'SSRF',open_redirect:'Open Redirect',crlf_injection:'CRLF Injection',ssti:'SSTI',
  command_injection:'OS Command Injection',command_injection_oast:'Command Injection OAST',command_injection_timing:'Command Injection Timing',sms_abuse:'SMS Abuse',sensitive_data:'Sensitive Data',
  cors:'CORS',security_headers:'Security Headers',http_trace:'HTTP TRACE',idor:'IDOR',csrf:'CSRF',method_override:'Method Override',mass_assignment:'Mass Assignment',mass_assignment_extended:'Mass Assignment Extended',
  nosql_injection:'NoSQL Injection',ldap_injection:'LDAP Injection',xpath_injection:'XPath Injection',java_deserialization:'Java Deserialization',java_expression:'Java Expression',java_expression_extended:'Java Expression Extended',jndi_injection:'JNDI Injection',
  shiro:'Shiro',jwt_weak:'JWT Weakness',jwt_active:'JWT Active',host_header_injection:'Host Header Injection',api_exposure:'API Exposure',spring_actuator:'Spring Actuator',graphql_security:'GraphQL Security',graphql_alias_abuse:'GraphQL Alias Abuse',
  json_polymorphic:'JSON Polymorphic',mybatis_dynamic_sql:'MyBatis Dynamic SQL',error_disclosure:'Error Disclosure',error_disclosure_extended:'Error Disclosure Extended',parameter_confusion:'Parameter Confusion',path_normalization:'Path Normalization',proxy_trust_bypass:'Proxy Trust Bypass'
};
function configPluginName(id){return state.plugins.find(v=>v.id===id)?.name||({sqli_extended:'SQL 扩展规则',sqli_timing:'SQL 时间注入规则',sqli_limit:'SQL 分页注入规则',sqli_order_by:'SQL 排序注入规则',mybatis_dynamic_sql:'MyBatis 动态 SQL 规则'}[id])||id}
function configPluginLabel(id){return `${configPluginName(id)} / ${configPluginEnglish[id]||id}`}
function initRuleEditor(){
  if(!state.config)return;
  const ids=Object.keys(state.config.plugin_rules||{}).filter(id=>id!=='file_read_encoded'),used=new Set();
  const groups=pluginGroups.map((g,index)=>({...g,index,ids:g.ids.filter(id=>ids.includes(id))}));
  groups[0].ids.push(...ids.filter(id=>(id.startsWith('sqli_')||id==='mybatis_dynamic_sql')&&!groups[0].ids.includes(id)));
  groups.forEach(g=>g.ids.forEach(id=>used.add(id)));
  groups.push({name:'其他插件规则',index:7,ids:ids.filter(id=>!used.has(id))});
  $('cfg-rule-plugin').innerHTML=groups.filter(g=>g.ids.length).map(g=>`<section class="config-plugin-group tone-${g.index}"><h3>${esc(g.name)}</h3><div class="config-plugin-grid">${g.ids.map(id=>`<div class="config-plugin-entry"><button type="button" class="plugin-item plugin-compact config-plugin-card" data-rule-id="${esc(id)}" aria-pressed="false" aria-expanded="false" aria-controls="config-plugin-detail"><span><strong>${esc(configPluginName(id))}</strong><small class="plugin-code">${esc(configPluginEnglish[id]||id)}</small><small class="config-plugin-hint">点击展开配置</small></span></button></div>`).join('')}</div></section>`).join('');
  state.ruleId=null;
  $('config-plugin-detail').hidden=true;
  $('cfg-rule-plugin').addEventListener('click',event=>{const button=event.target.closest('[data-rule-id]');if(!button)return;try{const nextId=button.dataset.ruleId;if(state.ruleId===nextId&&!$('config-plugin-detail').hidden){captureRule();collapseRule();return}captureRule();state.ruleId=nextId;showRule(state.ruleId)}catch(error){toast(error.message,true)}});
  $('format-rule-json').addEventListener('click',()=>{if(!state.ruleId)return;try{captureRule();showRule(state.ruleId);toast('规则 JSON 已格式化')}catch(error){toast(error.message,true)}});
}
function collapseRule(){
  const detail=$('config-plugin-detail');
  document.querySelectorAll('.config-plugin-entry.expanded').forEach(item=>item.classList.remove('expanded'));
  document.querySelectorAll('[data-rule-id]').forEach(button=>{button.setAttribute('aria-pressed','false');button.setAttribute('aria-expanded','false');const hint=button.querySelector('.config-plugin-hint');if(hint)hint.textContent='点击展开配置'});
  detail.hidden=true;
  state.ruleId=null;
}
function showRule(id){
  if(!id)return;
  const scrollX=window.scrollX,scrollY=window.scrollY;
  document.querySelectorAll('[data-rule-id]').forEach(button=>{const selected=button.dataset.ruleId===id;button.setAttribute('aria-pressed',String(selected));button.setAttribute('aria-expanded',String(selected));const hint=button.querySelector('.config-plugin-hint');if(hint)hint.textContent=selected?'再次点击收起':'点击展开配置'});
  const detail=$('config-plugin-detail'),entry=document.querySelector(`[data-rule-id="${CSS.escape(id)}"]`)?.closest('.config-plugin-entry');
  document.querySelectorAll('.config-plugin-entry.expanded').forEach(item=>item.classList.remove('expanded'));
  if(entry&&detail.parentElement!==entry)entry.appendChild(detail);
  if(entry)entry.classList.add('expanded');
  detail.hidden=false;
  $('config-plugin-title').textContent=configPluginLabel(id)+' · 配置项';
  $('config-sms-fields').hidden=id!=='sms_abuse';
  $('config-sql-fields').hidden=!id.startsWith('sqli');
  document.querySelector('.rule-allowlist-field').hidden=id!=='unauthorized';
  window.scrollTo(scrollX,scrollY);
  requestAnimationFrame(()=>window.scrollTo(scrollX,scrollY));
  const rule=state.config.plugin_rules?.[id]||{};setLines('cfg-rule-parameters',rule.parameter_names);setLines('cfg-rule-url-keywords',rule.url_keywords);setLines('cfg-rule-paths',rule.paths);setLines('cfg-rule-allow-paths',rule.allow_paths);$('cfg-rule-payloads').value=JSON.stringify(rule.payloads||[],null,2);$('cfg-rule-patterns').value=JSON.stringify(rule.patterns||[],null,2);$('rule-status').textContent=`${(rule.payloads||[]).length} Payload · ${(rule.patterns||[]).length} 正则`;
}
function parseRuleArray(id,label){let value;try{value=JSON.parse($(id).value||'[]')}catch(error){throw new Error(`${label} JSON 格式错误：${error.message}`)}if(!Array.isArray(value))throw new Error(`${label} 必须是 JSON 数组`);return value}
function captureRule(){if(!state.ruleId)return;const rule={...state.config.plugin_rules[state.ruleId],parameter_names:lines($('cfg-rule-parameters').value),url_keywords:lines($('cfg-rule-url-keywords').value),paths:lines($('cfg-rule-paths').value),allow_paths:lines($('cfg-rule-allow-paths').value),payloads:parseRuleArray('cfg-rule-payloads','Payload'),patterns:parseRuleArray('cfg-rule-patterns','检测正则')};state.config.plugin_rules[state.ruleId]=rule;$('rule-status').textContent=`${rule.payloads.length} Payload · ${(rule.patterns||[]).length} 正则`}


async function loadGuide(){
  const content=$('guide-content'),toc=$('guide-toc');
  if(!content||!toc)return;
  try{
    const response=await fetch('/plugins.md?v=3.13.0');
    if(!response.ok)throw new Error(`使用说明读取失败 (${response.status})`);
    const rendered=renderMarkdown(await response.text());
    content.innerHTML=rendered.html;
    toc.innerHTML=rendered.headings.filter(item=>item.level<=3).map(item=>`<a class="toc-level-${item.level}" href="#${esc(item.id)}">${esc(item.text)}</a>`).join('');
  }catch(error){content.innerHTML=`<p>${esc(error.message)}</p>`;toc.innerHTML='<span>目录不可用</span>'}
}

function renderMarkdown(source){
  const rows=String(source||'').replace(/\r\n/g,'\n').split('\n'),headings=[],used=new Map();
  let html='',index=0,list='';
  const closeList=()=>{if(list){html+=`</${list}>`;list=''}};
  const inline=value=>esc(value).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g,'<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>');
  const slug=text=>{const base=text.toLowerCase().replace(/<[^>]+>/g,'').replace(/[^\p{L}\p{N}]+/gu,'-').replace(/^-|-$/g,'')||'section';const count=used.get(base)||0;used.set(base,count+1);return count?`${base}-${count+1}`:base};
  while(index<rows.length){
    const line=rows[index];
    if(line.startsWith('```')){closeList();const lang=line.slice(3).trim();const code=[];index++;while(index<rows.length&&!rows[index].startsWith('```'))code.push(rows[index++]);html+=`<pre><code data-language="${esc(lang)}">${esc(code.join('\n'))}</code></pre>`;index++;continue}
    const heading=line.match(/^(#{1,4})\s+(.+)$/);if(heading){closeList();const level=heading[1].length,text=heading[2].replace(/\*\*/g,'').replace(/`/g,'');const id=slug(text);headings.push({level,text,id});html+=`<h${level} id="${esc(id)}">${inline(heading[2])}</h${level}>`;index++;continue}
    if(line.includes('|')&&index+1<rows.length&&/^\s*\|?\s*:?-{3,}/.test(rows[index+1])){closeList();const split=value=>value.replace(/^\s*\||\|\s*$/g,'').split('|').map(v=>v.trim());const header=split(line);index+=2;const body=[];while(index<rows.length&&rows[index].includes('|')&&rows[index].trim())body.push(split(rows[index++]));html+='<div class="markdown-table-wrap"><table><thead><tr>'+header.map(v=>`<th>${inline(v)}</th>`).join('')+'</tr></thead><tbody>'+body.map(cells=>'<tr>'+cells.map(v=>`<td>${inline(v)}</td>`).join('')+'</tr>').join('')+'</tbody></table></div>';continue}
    const bullet=line.match(/^\s*[-*]\s+(.+)$/),ordered=line.match(/^\s*\d+\.\s+(.+)$/);if(bullet||ordered){const type=ordered?'ol':'ul';if(list!==type){closeList();list=type;html+=`<${type}>`}html+=`<li>${inline((bullet||ordered)[1])}</li>`;index++;continue}
    if(!line.trim()){closeList();index++;continue}
    closeList();html+=`<p>${inline(line)}</p>`;index++;
  }
  closeList();return{html,headings};
}

window.HappyScanUI={api,esc,toast,formatTime,renderFinding,severityLabel,confidenceLabel,categoryLabel,severityClass,riskLabel,httpRequestEditor,parseParameterScopeText,decodeHTTPRequestPreview};
init();
